application: gpm-playlist
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup|internalupload).*
  script: gpm-playlist.wsgi.application
  login: admin
  secure: always

- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: gpm-playlist.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: playlist.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - \.storage.*
    - \.git
    - (.*)\.pyc
