application: gpm-playlist
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /favicon\.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon\.ico
    
  - url: /images/
    static_dir: static/images/
    secure: always
  
  - url: /_ah/(mapreduce|queue|warmup|internalupload).*
    script: playlist.wsgi.application
    login: admin
    secure: always

  - url: /static/admin/
    static_dir: sitepackages/django/contrib/admin/static/admin/
    secure: always
  
  - url: /static/manager/
    static_dir: static/manager/
    secure: always

  # Set Django admin to be login:admin as well as Django's is_staff restriction
  - url: /admin.*
    script: playlist.wsgi.application
    secure: always
    login: admin

  - url: /cron/.*
    script: playlist.wsgi.application
    secure: always
    login: admin

  - url: /manager/.*
    script: playlist.wsgi.application
    secure: always
    login: required

  - url: /.*
    script: playlist.wsgi.application
    secure: always

libraries:
  - name: pycrypto
    version: "2.6"
    
  - name: setuptools
    version: "0.6c11"
    
  - name: yaml
    version: "3.10"
    
  - name: ssl
    version: "2.7"

skip_files:
  - manage.py
  - README.md
  - install_deps
  - requirements.txt
  - sitepackages/google_appengine
  - \.storage.*
  - \.git
  - (.*)\.pyc
  - client
  - .*\.scss
  - .*\.md
  - .*\.gitignore
  - .*\.gzip
  - .*\.map
  - .*/LICENSE
  - sitepackages/Crypto
  - sitepackages/setuptools