---

tablename: album_art
columns:
    - name: 'id'
      type: Integer
      primary_key: true
      nullable: false
      autoincrement: 'auto'

    - name: 'kind'
      type: String
    - name: 'url'
      type: String
