tablename: primary_video
columns:
    - name: id
      type: String
      primary_key: true
      nullable: false

    - name: kind
      type: String

relationships:
    - name: thumbnails
      ref: VideoThumbnails
      backref:
          name: track
      primaryjoin: 'PrimaryVideo.id == VideoThumbnails.video_id'

