---

tablename: video_thumbnails
columns:
    - name: 'id'
      type: Integer
      primary_key: true
      nullable: false
      autoincrement: 'auto'

    - name: 'url'
      type: String

    - name: 'height'
      type: Integer

    - name: 'width'
      type: Integer

    - name: 'video_id'
      type: String
      nullable: false
