tablename: artist_art
columns:
    - name: 'id'
      type: Integer
      primary_key: true
      nullable: false

    - name: 'aspectRatio'
      type: String

    - name: 'autogen'
      type: Boolean

    - name: 'kind'
      type: String

    - name: 'url'
      type: String
